from __future__ import annotations

import argparse
from pathlib import Path


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Fine-tune a seq2seq model for classical Chinese translation.")
    parser.add_argument("--train_file", required=True, help="JSONL file generated by scripts/prepare_data.py")
    parser.add_argument("--validation_file", default=None, help="Optional validation JSONL file")
    parser.add_argument("--model_name", default="IDEA-CCNL/Randeng-BART-139M-SUMMARY")
    parser.add_argument("--output_dir", default="outputs/checkpoints/randeng-bart-classical-modern")
    parser.add_argument("--max_source_length", type=int, default=128)
    parser.add_argument("--max_target_length", type=int, default=128)
    parser.add_argument("--epochs", type=float, default=3)
    parser.add_argument("--batch_size", type=int, default=4)
    parser.add_argument("--learning_rate", type=float, default=5e-5)
    parser.add_argument("--logging_steps", type=int, default=50)
    parser.add_argument("--save_steps", type=int, default=1000)
    parser.add_argument("--eval_steps", type=int, default=1000)
    parser.add_argument("--max_train_samples", type=int, default=None)
    parser.add_argument(
        "--lambda_cycle",
        type=float,
        default=0.0,
        help="回环一致性损失权重。0=标准基线(对照组A)；>0=加回环约束(实验组B)，推荐 0.5~1.0",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    _validate_path(args.train_file, "Training file")
    if args.validation_file:
        _validate_path(args.validation_file, "Validation file")

    try:
        from datasets import load_dataset
        from transformers import (
            AutoModelForSeq2SeqLM,
            AutoTokenizer,
            DataCollatorForSeq2Seq,
            Seq2SeqTrainer,
            Seq2SeqTrainingArguments,
        )
    except ImportError as exc:
        raise SystemExit(
            "Missing training dependencies. Install them first:\n"
            "pip install torch transformers datasets accelerate sentencepiece"
        ) from exc

    data_files = {"train": args.train_file}
    if args.validation_file:
        data_files["validation"] = args.validation_file
    raw_datasets = load_dataset("json", data_files=data_files)
    if args.max_train_samples is not None:
        raw_datasets["train"] = raw_datasets["train"].select(
            range(min(args.max_train_samples, len(raw_datasets["train"])))
        )

    tokenizer = AutoTokenizer.from_pretrained(args.model_name, use_fast=False)
    model = AutoModelForSeq2SeqLM.from_pretrained(args.model_name)

    def preprocess_batch(batch: dict[str, list[str]]) -> dict[str, list[list[int]]]:
        model_inputs = tokenizer(
            batch["source"],
            max_length=args.max_source_length,
            truncation=True,
        )
        labels = tokenizer(
            text_target=batch["target"],
            max_length=args.max_target_length,
            truncation=True,
        )
        model_inputs["labels"] = labels["input_ids"]
        return model_inputs

    tokenized = raw_datasets.map(
        preprocess_batch,
        batched=True,
        remove_columns=raw_datasets["train"].column_names,
    )
    has_eval = "validation" in tokenized

    training_args = Seq2SeqTrainingArguments(
        output_dir=args.output_dir,
        learning_rate=args.learning_rate,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size,
        num_train_epochs=args.epochs,
        predict_with_generate=True,
        logging_steps=args.logging_steps,
        save_steps=args.save_steps,
        eval_steps=args.eval_steps if has_eval else None,
        eval_strategy="steps" if has_eval else "no",
        save_total_limit=2,
        report_to="none",
    )
    if args.lambda_cycle > 0:
        lambda_cycle = args.lambda_cycle

        class CycleSeq2SeqTrainer(Seq2SeqTrainer):
            """翻译损失 + λ×回环一致性损失（Soft Token 近似，端到端可导）。

            回环：源 A --(第一次前向, teacher forcing)--> 目标分布 B
                 softmax(B) @ Embedding 得到连续表示（绕过 argmax 不可导）
                 --(第二次前向, 连续表示作 encoder 输入)--> 重建源 A'
            cycle_loss = CE(A', A)
            """

            def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
                labels = inputs["labels"]
                attention_mask = inputs.get("attention_mask")

                # 第一次前向：源 -> 目标 logits，得标准翻译损失。
                outputs = model(
                    input_ids=inputs["input_ids"],
                    attention_mask=attention_mask,
                    labels=labels,
                )
                translation_loss = outputs.loss

                # Soft Token：用 softmax 概率加权词嵌入，得到连续的“目标”表示。
                embedding_matrix = model.get_input_embeddings().weight
                soft_embeds = outputs.logits.softmax(dim=-1) @ embedding_matrix

                # 第二次前向：连续表示作 encoder 输入，尝试重建源。
                # encoder mask 用目标的有效位置（labels != -100）；
                # 重建标签用源 input_ids，pad 位置置 -100 不计损失。
                cycle_attention = (labels != -100).long()
                source_labels = inputs["input_ids"].clone()
                if attention_mask is not None:
                    source_labels[attention_mask == 0] = -100
                cycle_outputs = model(
                    inputs_embeds=soft_embeds,
                    attention_mask=cycle_attention,
                    labels=source_labels,
                )

                loss = translation_loss + lambda_cycle * cycle_outputs.loss
                return (loss, outputs) if return_outputs else loss

        trainer_cls = CycleSeq2SeqTrainer
        print(f"[回环训练] lambda_cycle={lambda_cycle}（实验组 B）")
    else:
        trainer_cls = Seq2SeqTrainer
        print("[标准训练] 无回环约束（对照组 A）")

    trainer = trainer_cls(
        model=model,
        args=training_args,
        train_dataset=tokenized["train"],
        eval_dataset=tokenized["validation"] if has_eval else None,
        tokenizer=tokenizer,
        data_collator=DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model),
    )
    trainer.train()
    trainer.save_model(args.output_dir)
    tokenizer.save_pretrained(args.output_dir)


def _validate_path(path: str, label: str) -> None:
    if not Path(path).exists():
        raise FileNotFoundError(f"{label} not found: {path}")


if __name__ == "__main__":
    main()
